print('Hello world')
print("Hello world")
print('"Hello world"')
print('Day 1 - Python Print Function')
print("The function is declared like this:")
print("print('what to print')")
print("Hello world\nHello world\nHello world")
print("Hello"+"World")
print("Hello "+"World")
print("Hello"+" World")
print("Hello","World")

print("Hello"+" "+"World")